# See: https://docs.travis-ci.com/user/languages/dart/
language: dart
sudo: false
dart:
  - stable
  - dev
dart_task:
  - test
  - dartfmt
  - dartanalyze
branches:
  only: [master]
cache:
  directories:
    - $HOME/.pub-cache
